<?php
require_once __DIR__ . '/config.php';

try {
    echo "Creating database schema...\n";
    $schema = file_get_contents(__DIR__ . '/db/schema.sql');
    $statements = array_filter(array_map('trim', explode(';', $schema)));
    foreach ($statements as $statement) {
        if (!empty($statement)) {
            $pdo->exec($statement);
        }
    }
    
    echo "Clearing existing data...\n";
    $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
    $pdo->exec("TRUNCATE TABLE useful_expressions;");
    $pdo->exec("TRUNCATE TABLE training_sessions;");
    $pdo->exec("TRUNCATE TABLE weekly_progress;");
    $pdo->exec("TRUNCATE TABLE models;");
    $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");
    
    echo "Seeding models...\n";
    $stmt = $pdo->prepare("INSERT INTO models (type, number, title, prompt, content, useful_language, word_count) VALUES (?, ?, ?, ?, ?, ?, ?)");
    
    $models = [
        ["essay", 1, "Mobile phones in schools", "In your English class you have been talking about mobile phones in schools. Now your teacher has asked you to write an essay.\n\nWrite an essay using all the notes and giving reasons for your point of view.\n\n\"Schools should ban mobile phones during lessons.\" Do you agree?\nNotes: Write about the following points: 1. distraction  2. safety  3. ……………… (your own idea)\n\nWrite your essay in 140–190 words.", "Nowadays, mobile phones play a central role in teenagers' lives, and their use in schools has become a matter of ongoing debate. In this essay, I will look at two aspects: distraction and safety, before giving my own opinion.\nOn the one hand, there is no denying that phones can be a major source of distraction in class. Instead of paying attention to the teacher, many students tend to check messages or social media, which clearly has a negative effect on their learning.\nOn the other hand, it is worth remembering that phones can also serve as a useful safety tool, allowing parents to get in touch with their children in case of an emergency. What is more, when used properly, phones can provide access to educational apps and research tools.\nHaving considered both sides, I would argue that a complete ban is not the answer. Instead, schools should set clear rules about when phones can be used. In this way, students would benefit from the advantages without the drawbacks.", "{\"Introduction\": [\"Nowadays,\", \"...has become a matter of ongoing debate\", \"In this essay, I will look at...\"], \"Presenting one side\": [\"On the one hand,\", \"There is no denying that...\"], \"Presenting the other side\": [\"On the other hand,\", \"It is worth remembering that...\"], \"Addition\": [\"What is more,\"], \"Giving your opinion\": [\"Having considered both sides,\", \"I would argue that...\"], \"Conclusion\": [\"In this way,\", \"would benefit from... without...\"]}", 178],
        ["essay", 2, "Climate change responsibility", "In your English class you have been talking about climate change. Now your teacher has asked you to write an essay.\n\nWrite an essay using all the notes and giving reasons for your point of view.\n\n\"Individuals, not governments, are responsible for tackling climate change.\" Do you agree?\nNotes: Write about the following points: 1. individual actions  2. government policy  3. ……………… (your own idea)\n\nWrite your essay in 140–190 words.", "Climate change is undoubtedly one of the most pressing issues of our time, and there is ongoing debate about whether individuals or governments should be responsible for tackling it. This essay will examine both perspectives.\nFirstly, it could be argued that individuals have a duty to reduce their own environmental impact. Simple actions such as recycling, using public transport instead of cars, and cutting down on plastic can make a real difference when carried out by millions of people.\nHowever, many people believe that governments bear the greater responsibility, since they have the power to introduce policies that affect entire industries. For instance, investing in renewable energy and imposing stricter regulations on pollution would have a far greater impact than individual efforts alone.\nIn my view, both individuals and governments need to work together. While personal choices matter, without strong government action, real change is unlikely to happen. Ultimately, tackling climate change requires a shared effort at every level of society.", "{\"Introduction\": [\"...is undoubtedly one of the most pressing issues of our time\", \"This essay will examine...\"], \"Sequencing\": [\"Firstly,\"], \"Giving examples\": [\"Simple actions such as...\", \"For instance,\"], \"Contrast\": [\"However,\"], \"Cause / Result\": [\"since...\", \"would have a far greater impact than...\"], \"Opinion\": [\"In my view,\", \"both... and...\", \"while...\"], \"Conclusion\": [\"Ultimately,\", \"...requires a shared effort\"]}", 175],
        ["essay", 3, "Social media and teenagers", "In your English class you have been talking about social media. Now your teacher has asked you to write an essay.\n\nWrite an essay using all the notes and giving reasons for your point of view.\n\n\"Social media does more harm than good for teenagers.\" Do you agree?\nNotes: Write about the following points: 1. staying connected  2. mental health  3. ……………… (your own idea)\n\nWrite your essay in 140–190 words.", "These days, it is hard to imagine life without social media, especially for teenagers. While it offers clear benefits, it also raises some concerns.\nOn the positive side, social media enables young people to stay connected with friends no matter where they are. In addition, it provides a platform for self-expression and can help teenagers discover new interests and communities.\nNevertheless, there are also significant drawbacks. Spending excessive time online can lead to anxiety and low self-esteem, particularly when teenagers compare themselves to others. Moreover, exposure to inappropriate content remains a serious concern for many parents.\nWeighing up the arguments, I would say that social media is neither entirely good nor bad – it all depends on how it is used. Provided that teenagers use it responsibly and in moderation, the benefits can outweigh the risks.", "{\"Introduction\": [\"These days,\", \"It is hard to imagine...\"], \"Presenting benefits\": [\"On the positive side,\", \"enables... to...\", \"provides a platform for...\"], \"Presenting drawbacks\": [\"Nevertheless,\", \"there are also significant drawbacks\", \"lead to...\"], \"Addition\": [\"In addition,\", \"Moreover,\"], \"Weighing up / opinion\": [\"Weighing up the arguments,\", \"it all depends on...\", \"provided that...\"], \"Conclusion\": [\"...the benefits can outweigh the risks\"]}", 160],
        ["essay", 4, "Saving money from a young age", "In your English class you have been talking about money. Now your teacher has asked you to write an essay.\n\nWrite an essay using all the notes and giving reasons for your point of view.\n\n\"It is important to save money from a young age.\" Do you agree?\nNotes: Write about the following points: 1. good habits  2. financial security  3. ……………… (your own idea)\n\nWrite your essay in 140–190 words.", "Money management is a skill that, in my opinion, should be taught from an early age. This essay will explore why saving money while young brings clear advantages.\nTo start with, learning to save early helps young people develop good financial habits that last a lifetime. Rather than spending impulsively, those who save tend to think more carefully about their purchases. As a result, they are less likely to get into debt later in life.\nFurthermore, having savings provides a sense of security. Whether it's for emergencies or future goals such as university or travel, money set aside can make a real difference when unexpected costs arise.\nAdmittedly, some might argue that young people should enjoy their money while they can, without worrying about the future. Even so, I firmly believe that a balance can be struck. In conclusion, teaching children to save is an investment in their future that is well worth making.", "{\"Introduction\": [\"...is a skill that, in my opinion, should be...\", \"This essay will explore...\"], \"Sequencing\": [\"To start with,\", \"Furthermore,\"], \"Contrast\": [\"Rather than...\", \"Admittedly,\", \"Even so,\"], \"Result\": [\"As a result,\"], \"Correlatives\": [\"Whether it's... or...\", \"such as...\"], \"Opinion\": [\"I firmly believe that...\"], \"Conclusion\": [\"In conclusion,\", \"...is an investment in... that is well worth making\"]}", 173],
        ["essay", 5, "Travel broadens the mind", "In your English class you have been talking about travelling. Now your teacher has asked you to write an essay.\n\nWrite an essay using all the notes and giving reasons for your point of view.\n\n\"Travel broadens the mind.\" Do you agree?\nNotes: Write about the following points: 1. understanding other cultures  2. personal growth  3. ……………… (your own idea)\n\nWrite your essay in 140–190 words.", "\"Travel broadens the mind\" is a well-known saying, and I completely agree with it. In this essay, I will explain why travelling is one of the most valuable experiences a person can have.\nFirst and foremost, travelling exposes us to different cultures, languages and ways of life. By experiencing these differences first-hand, we develop a greater understanding and tolerance of people who are different from us. This, in turn, helps to reduce prejudice and misunderstanding.\nIn addition, travelling often pushes us out of our comfort zone, which builds confidence and independence. Dealing with unfamiliar situations, such as navigating a foreign city or communicating in another language, teaches valuable life skills that cannot be learnt in a classroom.\nSome people claim that travelling is simply a luxury that not everyone can afford. While this is partly true, even short trips close to home can offer similar benefits. All things considered, I am convinced that travel is an enriching experience that broadens our horizons in ways nothing else can.", "{\"Introduction\": [\"...is a well-known saying, and I completely agree with it\", \"In this essay, I will explain why...\"], \"Sequencing\": [\"First and foremost,\", \"In addition,\"], \"Cause / Result\": [\"This, in turn, helps to...\", \"which builds...\"], \"Giving examples\": [\"such as... or...\"], \"Conceding a counter-argument\": [\"Some people claim that...\", \"While this is partly true,\"], \"Conclusion\": [\"All things considered,\", \"I am convinced that...\"]}", 185],
        ["email", 1, "New job update", "This is part of an email you receive from your English friend, Chloe:\n\n\"...I heard you started a new job! How's it going so far? Write back and tell me all about it.\"\n\nWrite your email in 140–190 words.", "Hi Chloe,\nIt was so lovely to hear from you – I've been meaning to write for ages!\nTo answer your question, the new job is going really well so far. I have to admit I was a bit nervous at first, but everyone has been really welcoming. The best thing about it is that I get to work on projects I'm really passionate about. Having said that, it's been quite tiring, as I'm still getting used to the new routine.\nAs for your news, congratulations on finishing your course! You must be so relieved. Have you decided what you want to do next? I'd love to hear all about it.\nBy the way, why don't we meet up sometime soon? It would be great to catch up properly.\nLooking forward to hearing from you, Sam", "{\"Opening\": [\"It was so lovely to hear from you\", \"I've been meaning to write for ages\"], \"Answering a question\": [\"To answer your question,\", \"I have to admit...\"], \"Contrast\": [\"Having said that,\"], \"Introducing a new point\": [\"As for your news,\", \"By the way,\"], \"Congratulating\": [\"Congratulations on...!\", \"You must be...\"], \"Suggesting\": [\"Why don't we...?\", \"It would be great to...\"], \"Closing\": [\"Looking forward to hearing from you,\"]}", 148],
        ["email", 2, "Concert experience", "This is part of an email you receive from your English friend, Marco:\n\n\"...I heard you went to see your favourite band live last week! What was it like? Write and tell me everything!\"\n\nWrite your email in 140–190 words.", "Hi Marco,\nGreat to hear from you, as always! You won't believe how amazing the concert was.\nHonestly, it was one of the best nights of my life. The atmosphere was incredible, and the band played all my favourite songs. What really stood out was the moment they played their new single live for the first time – the whole crowd went wild!\nOn top of that, I managed to get a great spot near the front, so I could see everything clearly. The only downside was that it was absolutely packed, which made it a bit uncomfortable at times.\nAnyway, I definitely think you should try to go if they tour again. I'll let you know if I hear anything about new dates.\nTalk soon, Alex", "{\"Opening\": [\"Great to hear from you, as always!\", \"You won't believe...\"], \"Emphasis\": [\"Honestly,\", \"What really stood out was...\"], \"Addition\": [\"On top of that,\"], \"Result\": [\"so...\"], \"Mentioning a negative point\": [\"The only downside was...\"], \"Recommending / promising\": [\"I definitely think you should...\", \"I'll let you know...\"], \"Closing\": [\"Talk soon,\"]}", 147],
        ["email", 3, "Study abroad advice", "This is part of an email you receive from your English friend, Sophie:\n\n\"...I've decided to apply to study abroad next year, but I'm not sure where to start. Any advice?\"\n\nWrite your email in 140–190 words.", "Hi Sophie,\nThanks so much for your email – that's really exciting news!\nFirst of all, congratulations on making such a big decision. In terms of where to start, I'd suggest researching a few universities that offer the course you're interested in. It's also worth checking whether they provide support for international students, as this can make a huge difference.\nAnother thing to consider is the cost of living in each country – some places are far more expensive than others. If I were you, I'd also try to get in touch with students who have already studied there; they can give you honest, first-hand advice.\nOne last tip: don't leave the paperwork until the last minute, as visa applications can take a while.\nI really hope this helps – let me know how it goes!\nBest, Laura", "{\"Opening\": [\"Thanks so much for your email –\", \"that's really exciting news\"], \"Structuring advice\": [\"First of all,\", \"Another thing to consider is...\", \"One last tip:\"], \"Giving advice\": [\"I'd suggest...\", \"It's also worth checking...\", \"If I were you, I'd...\"], \"Cause\": [\"as...\"], \"Warning\": [\"don't leave... until the last minute\"], \"Closing\": [\"I really hope this helps –\", \"let me know how it goes\"]}", 155],
        ["email", 4, "Exam stress tips", "This is part of an email you receive from your English friend, Dan:\n\n\"...Exams are coming up and I'm feeling really stressed. Do you have any tips?\"\n\nWrite your email in 140–190 words.", "Hi Dan,\nI'm sorry to hear you've been feeling so stressed – exam season is never easy!\nFrom my own experience, one thing that really helped me was making a study timetable so that I could spread my revision out instead of cramming everything at the last minute. It's also a good idea to take regular breaks, as studying for hours without stopping tends to be counterproductive.\nAnother tip is to practise past papers under timed conditions – this really helped me get used to the pressure of the exam itself. On top of that, try not to compare yourself to other people; everyone works at their own pace.\nMost importantly, make sure you get enough sleep and look after yourself during this period.\nI really hope this helps – you're going to do great! Let me know if you need anything.\nTake care, Priya", "{\"Showing empathy\": [\"I'm sorry to hear...\", \"...is never easy\"], \"Giving advice from experience\": [\"From my own experience,\", \"one thing that really helped me was...\"], \"Sequencing tips\": [\"Another tip is to...\", \"On top of that,\", \"Most importantly,\"], \"Purpose\": [\"so that...\"], \"Contrast\": [\"instead of...\"], \"Encouragement\": [\"you're going to do great!\"], \"Closing\": [\"I really hope this helps –\", \"Take care,\"]}", 158],
        ["email", 5, "New hobby", "This is part of an email you receive from your English friend, Tom:\n\n\"...I heard you've taken up a new hobby recently. What made you start, and do you enjoy it?\"\n\nWrite your email in 140–190 words.", "Hi Tom,\nThanks for asking – I'd love to tell you all about it!\nA few months ago, I decided to try rock climbing, mainly because a few friends of mine kept telling me how much fun it was. At first, I have to admit I was a little intimidated, but it didn't take long for me to get hooked.\nWhat I love most about it is the sense of achievement you get every time you reach the top. It's also a great way to stay fit without it feeling like a chore, which, to be honest, is exactly what I needed.\nIf you're looking for a new hobby yourself, I'd really recommend giving it a go. There's a climbing centre not far from where you live, so maybe we could go together sometime?\nLet me know what you think! Speak soon, Ellie", "{\"Opening\": [\"Thanks for asking –\", \"I'd love to tell you all about it\"], \"Narrating a decision\": [\"A few months ago, I decided to...\", \"mainly because...\"], \"Contrast\": [\"At first..., but...\"], \"Explaining what you like\": [\"What I love most about it is...\", \"to be honest,\"], \"Recommending\": [\"If you're looking for...\", \"I'd really recommend...\", \"giving it a go\"], \"Suggesting plans\": [\"so maybe we could...?\"], \"Closing\": [\"Let me know what you think!\", \"Speak soon,\"]}", 153],
        ["article", 1, "Learning a foreign language", "You see this announcement on an international website for students:\n\nArticles wanted! What is the best way to learn a foreign language? Send us your tips and the best articles will be published next month.\n\nWrite your article in 140–190 words.", "Learning a new language can seem like a daunting task, but, in my experience, a few simple strategies can make all the difference.\nTo begin with, surrounding yourself with the language as much as possible is essential. Whether it's watching films, listening to music or following social media accounts in that language, this kind of exposure helps enormously.\nAnother key tip is to practise speaking from day one, even if you make mistakes. After all, the only way to improve is to actually use the language, rather than just studying grammar rules.\nIt's also worth finding a study method that suits you – some people prefer apps, while others learn better through conversation classes.\nAbove all, consistency is key. Even ten minutes a day can lead to noticeable progress over time. So, whatever method you choose, the most important thing is to keep going.", "{\"Introduction\": [\"...can seem like a daunting task, but, in my experience...\"], \"Sequencing tips\": [\"To begin with,\", \"Another key tip is to...\", \"Above all,\"], \"Giving examples / options\": [\"Whether it's... or...\", \"some people prefer..., while others...\"], \"Justifying\": [\"After all,\", \"rather than...\"], \"Result\": [\"can lead to...\"], \"Conclusion\": [\"So, whatever... the most important thing is to...\"]}", 156],
        ["article", 2, "Volunteering for young people", "You see this announcement on a website for teenagers:\n\nArticles wanted! Why is volunteering a great experience for young people? Send us your article!\n\nWrite your article in 140–190 words.", "Have you ever thought about giving up some of your free time to help others? If not, it might be time to consider it.\nOne of the main benefits of volunteering is that it allows young people to develop new skills that aren't always taught at school, such as teamwork, communication and problem-solving. What's more, these skills look great on a CV and can help you stand out when applying for jobs.\nOn top of that, volunteering gives you the chance to meet new people and make a real difference in your community. There's nothing quite like the feeling of helping someone in need.\nSome people worry that they simply don't have enough time. However, even a couple of hours a month can have a positive impact.\nAll things considered, volunteering is a win-win: not only does it benefit the community, but it also helps you grow as a person. Why not give it a try?", "{\"Engaging introduction\": [\"Have you ever thought about...?\", \"If not, it might be time to...\"], \"Listing benefits\": [\"One of the main benefits of... is that...\", \"What's more,\", \"On top of that,\"], \"Giving examples\": [\"such as...\"], \"Addressing a counter-argument\": [\"Some people worry that...\", \"However,\"], \"Conclusion\": [\"All things considered,\", \"not only... but...\", \"Why not give it a try?\"]}", 162],
        ["article", 3, "Social media and friendships", "You see this announcement on a lifestyle website:\n\nArticles wanted! How has social media changed friendships? We want to hear your views.\n\nWrite your article in 140–190 words.", "There's no doubt that social media has completely transformed the way we make and maintain friendships. But has this change been for the better?\nOn the one hand, platforms such as Instagram and WhatsApp make it easier than ever to stay in touch with friends, no matter the distance. Thanks to these apps, friendships that might have faded can now be kept alive.\nOn the other hand, some argue that social media has made friendships more superficial. Instead of spending quality time together, many people simply like or comment on each other's posts, which isn't quite the same as real connection.\nPersonally, I believe the key lies in balance. Using social media to arrange to meet up in person, rather than as a replacement for it, is surely the best approach.\nIn the end, technology is just a tool – it's up to us to use it wisely.", "{\"Introduction\": [\"There's no doubt that...\", \"But has this been for the better?\"], \"Balancing two sides\": [\"On the one hand,\", \"On the other hand,\", \"some argue that...\"], \"Cause\": [\"Thanks to...\"], \"Contrast\": [\"Instead of...\", \"rather than...\"], \"Personal opinion\": [\"Personally, I believe...\", \"the key lies in...\"], \"Conclusion\": [\"In the end,\", \"it's up to us to...\"]}", 160],
        ["article", 4, "Favourite free time activity", "You see this announcement on a magazine website:\n\nArticles wanted! What's your favourite way to spend your free time, and why?\n\nWrite your article in 140–190 words.", "We all lead increasingly busy lives, so finding the right way to relax really matters.\nFor me, nothing beats spending time outdoors. Whether it's going for a long walk, cycling or simply sitting in the park with a book, being in nature helps me switch off from the stress of daily life.\nAnother activity I really enjoy is cooking. There's something incredibly satisfying about trying out a new recipe and sharing the results with friends or family. Not only is it relaxing, but it also feels rewarding once the meal is ready.\nOf course, everyone is different, and what works for one person might not work for another. Some people prefer more active pursuits, such as sport, while others find peace in quieter hobbies like reading or painting.\nWhatever you choose, the important thing is to make time for the things you enjoy. After all, life is about more than just work.", "{\"Introduction\": [\"We all lead increasingly busy lives, so...\"], \"Expressing preference\": [\"For me, nothing beats...\", \"Another activity I really enjoy is...\"], \"Emphasis / correlatives\": [\"Not only... but...\"], \"Acknowledging different views\": [\"Of course, everyone is different,\", \"some... while others...\"], \"Giving examples\": [\"such as...\", \"like...\"], \"Conclusion\": [\"Whatever you choose,\", \"the important thing is to...\", \"After all,\"]}", 157],
        ["article", 5, "Surviving exam season", "You see this announcement on your college website:\n\nArticles wanted! Do you have any tips for surviving exam season? Share them with us!\n\nWrite your article in 140–190 words.", "Exam season can feel overwhelming, but, with the right approach, it doesn't have to be.\nFirst and foremost, organisation is key. Drawing up a realistic study timetable well in advance helps you avoid last-minute panic. It's also a good idea to break your revision down into manageable chunks, rather than trying to cover everything in one sitting.\nEqually important is looking after your wellbeing. Getting enough sleep, eating properly and taking regular breaks can significantly improve your concentration and memory.\nAnother useful tip is to practise with past exam papers, as this helps you get used to the format and timing of the real thing.\nFinally, try not to compare yourself to classmates – everyone has their own pace. With a bit of planning and self-care, exam season can be managed far more smoothly than you'd expect.", "{\"Introduction\": [\"...can feel overwhelming, but, with the right approach...\"], \"Sequencing tips\": [\"First and foremost,\", \"Equally important is...\", \"Another useful tip is to...\", \"Finally,\"], \"Contrast\": [\"rather than...\"], \"Cause\": [\"as this helps you...\"], \"Advice\": [\"try not to...\", \"It's also a good idea to...\"], \"Conclusion\": [\"With a bit of..., ... can be managed far more smoothly than you'd expect\"]}", 153],
        ["review", 1, "Restaurant review", "You see this announcement on a website:\n\nReviews wanted! Tell us about a restaurant you have visited recently.\n\nWrite your review in 140–190 words.", "Last weekend, I decided to try out a new restaurant that had recently opened in the city centre, and overall, I was thoroughly impressed.\nFrom the moment we walked in, the atmosphere was warm and inviting, with cosy lighting and friendly staff who made us feel welcome straight away.\nAs for the food, I have to say it exceeded my expectations. The starter, a homemade soup, was bursting with flavour, and the main course – a grilled salmon dish – was cooked to perfection. What impressed me most was how fresh all the ingredients tasted.\nOn the downside, the service was a little slow during the busiest part of the evening, which was a minor inconvenience. Prices, however, were more than reasonable for the quality on offer.\nWould I go back? Without a doubt. If you're looking for a relaxed evening out with great food, this place is well worth a visit. I'd give it four stars out of five.", "{\"Introduction\": [\"Last weekend, I decided to try out...\", \"...and overall, I was thoroughly impressed\"], \"Describing atmosphere\": [\"From the moment we walked in,\"], \"Discussing a specific aspect\": [\"As for the food,\", \"I have to say...\", \"What impressed me most was...\"], \"Negative points\": [\"On the downside,\", \"...was a minor inconvenience\"], \"Contrast\": [\"however,\"], \"Recommendation\": [\"Would I go back? Without a doubt.\", \"well worth a visit\"], \"Rating\": [\"I'd give it ... out of five\"]}", 167],
        ["review", 2, "Book review", "You see this announcement on a book club website:\n\nReviews wanted! Tell us about a book you have read recently.\n\nWrite your review in 140–190 words.", "I recently finished reading \"The Last Lighthouse\", a mystery novel that had been recommended to me by several friends, and I can honestly say it didn't disappoint.\nThe story follows a young journalist investigating a series of strange events in a small coastal town. What I loved most about this book was the way the author builds suspense, keeping readers guessing right until the final chapter. The characters, too, were incredibly well developed, which made it easy to become invested in their stories.\nThat said, I did feel that the middle section dragged a little, with too much focus on minor details that didn't add much to the plot. Nevertheless, this didn't take away from my overall enjoyment.\nIn terms of writing style, it was both accessible and engaging, making it a real page-turner.\nOverall, I would highly recommend this book to anyone who enjoys a gripping mystery. A solid four out of five stars.", "{\"Introduction\": [\"I recently finished reading...\", \"...and I can honestly say it didn't disappoint\"], \"Describing plot\": [\"The story follows...\"], \"Positive points\": [\"What I loved most about this book was...\", \"...were incredibly well developed\"], \"Negative points (softened)\": [\"That said,\", \"I did feel that...\", \"Nevertheless,\"], \"Specifying an aspect\": [\"In terms of...\"], \"Recommendation\": [\"Overall, I would highly recommend...\", \"to anyone who enjoys...\"], \"Rating\": [\"A solid ... out of five stars\"]}", 164],
        ["review", 3, "Concert review", "You see this announcement on a music website:\n\nReviews wanted! Tell us about a live concert you have been to recently.\n\nWrite your review in 140–190 words.", "I recently attended a live concert by an up-and-coming local band, and, I have to admit, I wasn't quite prepared for how good it would be.\nFrom the opening song, the energy in the room was electric. The band's performance was outstanding, especially the lead singer, whose voice suited every song perfectly. What really stood out for me was the connection between the band and the audience – it felt like a genuinely intimate experience, despite the venue being packed.\nOn the downside, the sound quality was occasionally a little off, particularly during the faster songs, which made some lyrics hard to make out. This, however, was a small issue compared to the overall quality of the show.\nTicket prices were reasonable, and the venue itself had a great atmosphere.\nWould I recommend this band? Absolutely. If you enjoy live music with real passion behind it, this is a show well worth catching. I'd rate it four and a half stars out of five.", "{\"Introduction\": [\"I recently attended...\", \"I have to admit, I wasn't quite prepared for...\"], \"Describing the experience\": [\"From the opening song,\", \"What really stood out for me was...\"], \"Contrast within praise\": [\"despite...\"], \"Negative points\": [\"On the downside,\", \"particularly during...\"], \"Softening a criticism\": [\"This, however, was a small issue compared to...\"], \"Recommendation\": [\"Would I recommend...? Absolutely.\", \"well worth catching\"], \"Rating\": [\"I'd rate it ... out of five\"]}", 172],
        ["review", 4, "App review", "You see this announcement on a technology website:\n\nReviews wanted! Tell us about an app you have used recently.\n\nWrite your review in 140–190 words.", "I've been using a new productivity app called \"FocusFlow\" for the past month, and overall, it has genuinely changed the way I work.\nThe app's main feature is a simple timer system that helps you break your work into focused sessions with short breaks in between. What I particularly liked was how easy it was to use – the interface is clean, and there's nothing complicated about setting it up.\nAnother great feature is the progress tracker, which shows you exactly how much time you've spent working, making it incredibly motivating.\nOn the downside, some of the more advanced features are only available with a paid subscription, which might put off some users. Also, the app occasionally crashed during longer sessions, which was mildly frustrating.\nThat said, these issues didn't spoil my overall experience. If you struggle with procrastination or simply want to boost your productivity, I'd definitely recommend giving this app a try. I'd give it four stars out of five.", "{\"Introduction\": [\"I've been using... for the past month,\", \"...and overall, it has genuinely changed...\"], \"Describing features\": [\"The app's main feature is...\", \"Another great feature is...\"], \"Positive points\": [\"What I particularly liked was...\"], \"Negative points\": [\"On the downside,\", \"which might put off...\", \"Also,\"], \"Concession\": [\"That said, these issues didn't spoil...\"], \"Recommendation\": [\"If you struggle with... or..., I'd definitely recommend...\"], \"Rating\": [\"I'd give it ... out of five\"]}", 167],
        ["review", 5, "Exhibition review", "You see this announcement on a local website:\n\nReviews wanted! Tell us about an exhibition or museum you have visited recently.\n\nWrite your review in 140–190 words.", "Last month, I visited a new photography exhibition at the city's art museum, and, overall, it left a lasting impression on me.\nThe exhibition featured the work of several international photographers, each exploring the theme of \"change\" through striking images. What I found most impressive was the sheer variety on display – from powerful images of nature to thought-provoking urban scenes.\nThe layout of the exhibition was also well thought out, guiding visitors through each section smoothly. In addition, the information provided alongside each photograph added real depth to the experience.\nMy only criticism would be that the exhibition was quite crowded when we visited, making it difficult to appreciate some pieces properly. Booking a quieter time slot, therefore, might be a good idea.\nDespite this minor drawback, I would highly recommend this exhibition to anyone interested in photography or contemporary art. A well-deserved four out of five stars.", "{\"Introduction\": [\"Last month, I visited...\", \"...it left a lasting impression on me\"], \"Describing content\": [\"The exhibition featured...\", \"What I found most impressive was...\"], \"Addition\": [\"In addition,\"], \"Making a criticism (polite)\": [\"My only criticism would be that...\", \"making it difficult to...\"], \"Suggesting a solution\": [\"..., therefore, might be a good idea\"], \"Concession + recommendation\": [\"Despite this minor drawback, I would highly recommend...\"], \"Rating\": [\"A well-deserved ... out of five stars\"]}", 160],
        ["report", 1, "School trip evaluation", "Your class recently went on a school trip. Your teacher has asked you to write a report evaluating the trip and suggesting improvements for next year.\n\nWrite your report in 140–190 words.", "Introduction\nThe purpose of this report is to evaluate our recent class trip to the science museum and to suggest possible improvements for future visits.\nTransport and timing\nOverall, the coach journey went smoothly, although several students commented that the departure time was too early. A later start, therefore, might be worth considering.\nActivities\nWith regard to the activities, the general consensus was that the interactive exhibits were extremely popular. However, a number of students felt that the guided tour was too long, which resulted in reduced time for the exhibits themselves.\nLunch arrangements\nAs far as lunch is concerned, most students agreed that the picnic area was pleasant, but the queuing time for food was excessive.\nConclusion and recommendations\nTaking the above into account, I would recommend that future trips allow more free time for exhibits, shorten the guided tour, and consider bringing packed lunches to avoid queuing. These changes would, in my view, greatly improve the overall experience.", "{\"Introduction (purpose)\": [\"The purpose of this report is to...\", \"...and to suggest...\"], \"Presenting findings\": [\"Overall,\", \"With regard to...\", \"As far as ... is concerned,\"], \"Reporting opinions\": [\"several students commented that...\", \"the general consensus was that...\", \"a number of students felt that...\", \"most students agreed that...\"], \"Result\": [\"which resulted in...\"], \"Recommendations\": [\"I would recommend that...\", \"...might be worth considering\", \"and consider + -ing\"], \"Conclusion\": [\"Taking the above into account,\", \"These changes would, in my view, greatly improve...\"]}", 166],
        ["report", 2, "Part-time job opportunities", "Your college magazine has asked you to write a report on part-time job opportunities available for students in your area.\n\nWrite your report in 140–190 words.", "Introduction\nThe aim of this report is to provide an overview of part-time job opportunities available to students in the local area and to assess their suitability.\nRetail and hospitality\nA large number of part-time positions are currently available in local shops and cafés. These jobs, on the whole, offer flexible hours, which suits students with a busy timetable. However, the pay is often close to the minimum wage.\nTutoring\nAnother popular option is private tutoring, particularly for students who excel in a specific subject. This tends to be better paid, although finding clients can take time.\nOnline opportunities\nWith the rise of remote work, an increasing number of students are turning to online freelance work, such as graphic design or content writing. This option, it is worth noting, requires specific skills.\nConclusion and recommendations\nIn light of the above, I would recommend that the college create a dedicated noticeboard for local vacancies and offer workshops on freelance skills. This would help students make more informed choices about part-time work.", "{\"Introduction (purpose)\": [\"The aim of this report is to...\", \"...and to assess...\"], \"Presenting findings\": [\"A large number of...\", \"on the whole,\"], \"Contrast\": [\"However,\", \"although...\"], \"Introducing a trend\": [\"With the rise of...\", \"an increasing number of... are turning to...\"], \"Giving examples\": [\"such as... or...\"], \"Recommendations\": [\"I would recommend that...\", \"In light of the above,\"], \"Conclusion\": [\"This would help students...\"]}", 166],
        ["report", 3, "Town leisure facilities", "The local tourist board has asked you to write a report on the leisure facilities in your town and suggest ways to attract more visitors.\n\nWrite your report in 140–190 words.", "Introduction\nThis report aims to assess the current leisure facilities available in our town and to recommend ways of attracting more tourists.\nParks and outdoor spaces\nOverall, the town's parks are well maintained and provide pleasant spaces for walking and relaxing. Nevertheless, visitors have pointed out that signage is limited, making it difficult to find key attractions.\nRestaurants and cafés\nAs far as dining options are concerned, there is a good range of restaurants catering to different tastes and budgets. That said, many close early, which can be inconvenient for evening visitors.\nCultural attractions\nWith regard to cultural attractions, the local museum receives largely positive feedback, though its opening hours could be extended, particularly at weekends.\nConclusion and recommendations\nTaking everything into consideration, I would suggest that the tourist board improve signage throughout the town, encourage later opening hours for local businesses, and extend museum hours at weekends. These measures would, I believe, significantly boost tourism.", "{\"Introduction (purpose)\": [\"This report aims to...\", \"...and to recommend...\"], \"Presenting findings\": [\"Overall,\", \"As far as ... are concerned,\", \"With regard to...\"], \"Reporting feedback\": [\"visitors have pointed out that...\", \"the local museum receives largely positive feedback\"], \"Contrast\": [\"Nevertheless,\", \"That said,\", \"though...\"], \"Recommendations\": [\"I would suggest that...\", \"Taking everything into consideration,\"], \"Conclusion\": [\"These measures would, I believe, significantly...\"]}", 159],
        ["report", 4, "Student study habits", "Your college principal has asked you to write a report on students' study habits and to suggest how the library could better support them.\n\nWrite your report in 140–190 words.", "Introduction\nThe purpose of this report is to outline students' current study habits and to suggest how the library might better support their needs.\nCurrent study patterns\nAccording to a recent survey, the majority of students prefer to study in the evenings, often just before deadlines. This, in many cases, leads to rushed and less effective work.\nUse of the library\nWith regard to the library, feedback suggests that it is generally well used, although many students complained that quiet study areas are often full, particularly during exam periods.\nAccess to resources\nAs for online resources, a considerable number of students were unaware that the library offers digital access to journals and e-books, which suggests a need for better promotion.\nConclusion and recommendations\nIn light of these findings, I would recommend that the library increase the number of quiet study spaces, run introductory sessions on its digital resources, and consider extending its opening hours during exam periods. These steps would likely improve both study habits and outcomes.", "{\"Introduction (purpose)\": [\"The purpose of this report is to...\", \"...and to suggest...\"], \"Citing evidence\": [\"According to a recent survey,\", \"feedback suggests that...\"], \"Result\": [\"This, in many cases, leads to...\", \"which suggests a need for...\"], \"Contrast\": [\"although...\"], \"Reporting complaints\": [\"many students complained that...\", \"were unaware that...\"], \"Recommendations\": [\"I would recommend that...\", \"In light of these findings,\"], \"Conclusion\": [\"These steps would likely...\"]}", 165],
        ["report", 5, "Fundraising event comparison", "Your school is planning a fundraising event. The head teacher has asked you to write a report comparing possible options and recommending the best one.\n\nWrite your report in 140–190 words.", "Introduction\nThe aim of this report is to compare three possible fundraising events and to recommend the most suitable option for our school.\nOption 1: Sponsored walk\nA sponsored walk, on the one hand, requires little investment and could involve the whole school community. On the other hand, its success depends heavily on the weather and the number of sponsors each student can find.\nOption 2: Talent show\nA talent show, by contrast, tends to generate a lot of enthusiasm among students, as well as attracting parents as an audience. However, it requires considerable organisation and rehearsal time.\nOption 3: Bake sale\nFinally, a bake sale is quick to organise and appeals to all age groups, although it is likely to raise less money than the other two options.\nConclusion and recommendation\nHaving weighed up the options, I would recommend the talent show, since it offers the best balance between fundraising potential and community engagement. With careful planning, this event could prove highly successful.", "{\"Introduction (purpose)\": [\"The aim of this report is to compare...\", \"...and to recommend...\"], \"Comparing options\": [\"on the one hand,\", \"on the other hand,\", \"by contrast,\"], \"Addition\": [\"as well as...\"], \"Contrast\": [\"However,\", \"although...\"], \"Sequencing options\": [\"Finally,\"], \"Recommendation\": [\"Having weighed up the options, I would recommend...\", \"since...\"], \"Conclusion\": [\"With careful planning, this event could prove...\"]}", 168],
    ];

    foreach ($models as $model) {
        $stmt->execute($model);
    }
    
    echo "Seeding weekly progress...\n";
    $weeks = [
        [1, 'essay'], [2, 'email'], [3, 'article'], [4, 'review'], [5, 'report']
    ];
    $stmt2 = $pdo->prepare("INSERT INTO weekly_progress (week_number, writing_type) VALUES (?, ?)");
    foreach ($weeks as $w) {
        $stmt2->execute($w);
    }
    
    echo "Seeding useful expressions...\n";
    $stmt3 = $pdo->prepare("INSERT INTO useful_expressions (category, expression, writing_types) VALUES (?, ?, ?)");
    
    $expressions = [
        ["introduction", "Nowadays,", "essay"],
        ["introduction", "...has become a matter of ongoing debate", "essay"],
        ["introduction", "In this essay, I will look at...", "essay"],
        ["positive_points", "On the one hand,", "essay"],
        ["positive_points", "There is no denying that...", "essay"],
        ["contrast", "On the other hand,", "article,essay"],
        ["contrast", "It is worth remembering that...", "essay"],
        ["addition", "What is more,", "essay"],
        ["opinion", "Having considered both sides,", "essay"],
        ["opinion", "I would argue that...", "essay"],
        ["conclusion", "In this way,", "essay"],
        ["conclusion", "would benefit from... without...", "essay"],
        ["introduction", "...is undoubtedly one of the most pressing issues of our time", "essay"],
        ["introduction", "This essay will examine...", "essay"],
        ["sequence", "Firstly,", "essay"],
        ["examples", "Simple actions such as...", "essay"],
        ["examples", "For instance,", "essay"],
        ["contrast", "However,", "article,essay,report"],
        ["cause_result", "since...", "essay"],
        ["cause_result", "would have a far greater impact than...", "essay"],
        ["opinion", "In my view,", "essay"],
        ["opinion", "both... and...", "essay"],
        ["opinion", "while...", "essay"],
        ["conclusion", "Ultimately,", "essay"],
        ["conclusion", "...requires a shared effort", "essay"],
        ["introduction", "These days,", "essay"],
        ["introduction", "It is hard to imagine...", "essay"],
        ["positive_points", "On the positive side,", "essay"],
        ["positive_points", "enables... to...", "essay"],
        ["positive_points", "provides a platform for...", "essay"],
        ["negative_points", "Nevertheless,", "essay,review"],
        ["negative_points", "there are also significant drawbacks", "essay"],
        ["negative_points", "lead to...", "essay"],
        ["addition", "In addition,", "essay,review"],
        ["addition", "Moreover,", "essay"],
        ["opinion", "Weighing up the arguments,", "essay"],
        ["opinion", "it all depends on...", "essay"],
        ["opinion", "provided that...", "essay"],
        ["conclusion", "...the benefits can outweigh the risks", "essay"],
        ["introduction", "...is a skill that, in my opinion, should be...", "essay"],
        ["introduction", "This essay will explore...", "essay"],
        ["sequence", "To start with,", "essay"],
        ["sequence", "Furthermore,", "essay"],
        ["contrast", "Rather than...", "essay"],
        ["contrast", "Admittedly,", "essay"],
        ["contrast", "Even so,", "essay"],
        ["cause_result", "As a result,", "essay"],
        ["positive_points", "Whether it's... or...", "essay"],
        ["positive_points", "such as...", "essay"],
        ["opinion", "I firmly believe that...", "essay"],
        ["conclusion", "In conclusion,", "essay"],
        ["conclusion", "...is an investment in... that is well worth making", "essay"],
        ["introduction", "...is a well-known saying, and I completely agree with it", "essay"],
        ["introduction", "In this essay, I will explain why...", "essay"],
        ["sequence", "First and foremost,", "article,essay"],
        ["sequence", "In addition,", "essay"],
        ["cause_result", "This, in turn, helps to...", "essay"],
        ["cause_result", "which builds...", "essay"],
        ["examples", "such as... or...", "essay,report"],
        ["contrast", "Some people claim that...", "essay"],
        ["contrast", "While this is partly true,", "essay"],
        ["conclusion", "All things considered,", "article,essay"],
        ["conclusion", "I am convinced that...", "essay"],
        ["introduction", "It was so lovely to hear from you", "email"],
        ["introduction", "I've been meaning to write for ages", "email"],
        ["answering_a_question", "To answer your question,", "email"],
        ["answering_a_question", "I have to admit...", "email"],
        ["contrast", "Having said that,", "email"],
        ["introducing_a_new_point", "As for your news,", "email"],
        ["introducing_a_new_point", "By the way,", "email"],
        ["congratulating", "Congratulations on...!", "email"],
        ["congratulating", "You must be...", "email"],
        ["recommendation", "Why don't we...?", "email"],
        ["recommendation", "It would be great to...", "email"],
        ["email_closing", "Looking forward to hearing from you,", "email"],
        ["introduction", "Great to hear from you, as always!", "email"],
        ["introduction", "You won't believe...", "email"],
        ["positive_points", "Honestly,", "email"],
        ["positive_points", "What really stood out was...", "email"],
        ["addition", "On top of that,", "email"],
        ["cause_result", "so...", "email"],
        ["negative_points", "The only downside was...", "email"],
        ["recommendation", "I definitely think you should...", "email"],
        ["recommendation", "I'll let you know...", "email"],
        ["email_closing", "Talk soon,", "email"],
        ["introduction", "Thanks so much for your email –", "email"],
        ["introduction", "that's really exciting news", "email"],
        ["sequence", "First of all,", "email"],
        ["sequence", "Another thing to consider is...", "email"],
        ["sequence", "One last tip:", "email"],
        ["recommendation", "I'd suggest...", "email"],
        ["recommendation", "It's also worth checking...", "email"],
        ["recommendation", "If I were you, I'd...", "email"],
        ["cause_result", "as...", "email"],
        ["negative_points", "don't leave... until the last minute", "email"],
        ["email_closing", "I really hope this helps –", "email"],
        ["email_closing", "let me know how it goes", "email"],
        ["introduction", "I'm sorry to hear...", "email"],
        ["introduction", "...is never easy", "email"],
        ["recommendation", "From my own experience,", "email"],
        ["recommendation", "one thing that really helped me was...", "email"],
        ["sequence", "Another tip is to...", "email"],
        ["sequence", "On top of that,", "email"],
        ["sequence", "Most importantly,", "email"],
        ["cause_result", "so that...", "email"],
        ["contrast", "instead of...", "email"],
        ["email_closing", "you're going to do great!", "email"],
        ["email_closing", "Take care,", "email"],
        ["introduction", "Thanks for asking –", "email"],
        ["introduction", "I'd love to tell you all about it", "email"],
        ["sequence", "A few months ago, I decided to...", "email"],
        ["sequence", "mainly because...", "email"],
        ["contrast", "At first..., but...", "email"],
        ["positive_points", "What I love most about it is...", "email"],
        ["positive_points", "to be honest,", "email"],
        ["recommendation", "If you're looking for...", "email"],
        ["recommendation", "I'd really recommend...", "email"],
        ["recommendation", "giving it a go", "email"],
        ["recommendation", "so maybe we could...?", "email"],
        ["email_closing", "Let me know what you think!", "email"],
        ["email_closing", "Speak soon,", "email"],
        ["introduction", "...can seem like a daunting task, but, in my experience...", "article"],
        ["sequence", "To begin with,", "article"],
        ["sequence", "Another key tip is to...", "article"],
        ["sequence", "Above all,", "article"],
        ["examples", "Whether it's... or...", "article"],
        ["examples", "some people prefer..., while others...", "article"],
        ["positive_points", "After all,", "article"],
        ["positive_points", "rather than...", "article"],
        ["cause_result", "can lead to...", "article"],
        ["conclusion", "So, whatever... the most important thing is to...", "article"],
        ["introduction", "Have you ever thought about...?", "article"],
        ["introduction", "If not, it might be time to...", "article"],
        ["positive_points", "One of the main benefits of... is that...", "article"],
        ["positive_points", "What's more,", "article"],
        ["positive_points", "On top of that,", "article"],
        ["examples", "such as...", "article"],
        ["contrast", "Some people worry that...", "article"],
        ["conclusion", "not only... but...", "article"],
        ["conclusion", "Why not give it a try?", "article"],
        ["introduction", "There's no doubt that...", "article"],
        ["introduction", "But has this been for the better?", "article"],
        ["contrast", "On the one hand,", "article"],
        ["contrast", "some argue that...", "article"],
        ["cause_result", "Thanks to...", "article"],
        ["contrast", "Instead of...", "article"],
        ["contrast", "rather than...", "article"],
        ["opinion", "Personally, I believe...", "article"],
        ["opinion", "the key lies in...", "article"],
        ["conclusion", "In the end,", "article"],
        ["conclusion", "it's up to us to...", "article"],
        ["introduction", "We all lead increasingly busy lives, so...", "article"],
        ["positive_points", "For me, nothing beats...", "article"],
        ["positive_points", "Another activity I really enjoy is...", "article"],
        ["positive_points", "Not only... but...", "article"],
        ["contrast", "Of course, everyone is different,", "article"],
        ["contrast", "some... while others...", "article"],
        ["examples", "like...", "article"],
        ["conclusion", "Whatever you choose,", "article"],
        ["conclusion", "the important thing is to...", "article"],
        ["conclusion", "After all,", "article"],
        ["introduction", "...can feel overwhelming, but, with the right approach...", "article"],
        ["sequence", "Equally important is...", "article"],
        ["sequence", "Another useful tip is to...", "article"],
        ["sequence", "Finally,", "article,report"],
        ["cause_result", "as this helps you...", "article"],
        ["recommendation", "try not to...", "article"],
        ["recommendation", "It's also a good idea to...", "article"],
        ["conclusion", "With a bit of..., ... can be managed far more smoothly than you'd expect", "article"],
        ["introduction", "Last weekend, I decided to try out...", "review"],
        ["introduction", "...and overall, I was thoroughly impressed", "review"],
        ["positive_points", "From the moment we walked in,", "review"],
        ["positive_points", "As for the food,", "review"],
        ["positive_points", "I have to say...", "review"],
        ["positive_points", "What impressed me most was...", "review"],
        ["negative_points", "On the downside,", "review"],
        ["negative_points", "...was a minor inconvenience", "review"],
        ["contrast", "however,", "review"],
        ["recommendation", "Would I go back? Without a doubt.", "review"],
        ["recommendation", "well worth a visit", "review"],
        ["positive_points", "I'd give it ... out of five", "review"],
        ["introduction", "I recently finished reading...", "review"],
        ["introduction", "...and I can honestly say it didn't disappoint", "review"],
        ["positive_points", "The story follows...", "review"],
        ["positive_points", "What I loved most about this book was...", "review"],
        ["positive_points", "...were incredibly well developed", "review"],
        ["negative_points", "That said,", "review"],
        ["negative_points", "I did feel that...", "review"],
        ["positive_points", "In terms of...", "review"],
        ["recommendation", "Overall, I would highly recommend...", "review"],
        ["recommendation", "to anyone who enjoys...", "review"],
        ["positive_points", "A solid ... out of five stars", "review"],
        ["introduction", "I recently attended...", "review"],
        ["introduction", "I have to admit, I wasn't quite prepared for...", "review"],
        ["positive_points", "From the opening song,", "review"],
        ["positive_points", "What really stood out for me was...", "review"],
        ["contrast", "despite...", "review"],
        ["negative_points", "particularly during...", "review"],
        ["negative_points", "This, however, was a small issue compared to...", "review"],
        ["recommendation", "Would I recommend...? Absolutely.", "review"],
        ["recommendation", "well worth catching", "review"],
        ["positive_points", "I'd rate it ... out of five", "review"],
        ["introduction", "I've been using... for the past month,", "review"],
        ["introduction", "...and overall, it has genuinely changed...", "review"],
        ["positive_points", "The app's main feature is...", "review"],
        ["positive_points", "Another great feature is...", "review"],
        ["positive_points", "What I particularly liked was...", "review"],
        ["negative_points", "which might put off...", "review"],
        ["negative_points", "Also,", "review"],
        ["contrast", "That said, these issues didn't spoil...", "review"],
        ["recommendation", "If you struggle with... or..., I'd definitely recommend...", "review"],
        ["introduction", "Last month, I visited...", "review"],
        ["introduction", "...it left a lasting impression on me", "review"],
        ["positive_points", "The exhibition featured...", "review"],
        ["positive_points", "What I found most impressive was...", "review"],
        ["negative_points", "My only criticism would be that...", "review"],
        ["negative_points", "making it difficult to...", "review"],
        ["recommendation", "..., therefore, might be a good idea", "review"],
        ["contrast", "Despite this minor drawback, I would highly recommend...", "review"],
        ["positive_points", "A well-deserved ... out of five stars", "review"],
        ["introduction", "The purpose of this report is to...", "report"],
        ["introduction", "...and to suggest...", "report"],
        ["report_findings", "Overall,", "report"],
        ["report_findings", "With regard to...", "report"],
        ["report_findings", "As far as ... is concerned,", "report"],
        ["report_findings", "several students commented that...", "report"],
        ["report_findings", "the general consensus was that...", "report"],
        ["report_findings", "a number of students felt that...", "report"],
        ["report_findings", "most students agreed that...", "report"],
        ["cause_result", "which resulted in...", "report"],
        ["report_recommendations", "I would recommend that...", "report"],
        ["report_recommendations", "...might be worth considering", "report"],
        ["report_recommendations", "and consider + -ing", "report"],
        ["conclusion", "Taking the above into account,", "report"],
        ["conclusion", "These changes would, in my view, greatly improve...", "report"],
        ["introduction", "The aim of this report is to...", "report"],
        ["introduction", "...and to assess...", "report"],
        ["report_findings", "A large number of...", "report"],
        ["report_findings", "on the whole,", "report"],
        ["contrast", "although...", "report"],
        ["report_findings", "With the rise of...", "report"],
        ["report_findings", "an increasing number of... are turning to...", "report"],
        ["report_recommendations", "In light of the above,", "report"],
        ["conclusion", "This would help students...", "report"],
        ["introduction", "This report aims to...", "report"],
        ["introduction", "...and to recommend...", "report"],
        ["report_findings", "As far as ... are concerned,", "report"],
        ["report_findings", "visitors have pointed out that...", "report"],
        ["report_findings", "the local museum receives largely positive feedback", "report"],
        ["contrast", "Nevertheless,", "report"],
        ["contrast", "That said,", "report"],
        ["contrast", "though...", "report"],
        ["report_recommendations", "I would suggest that...", "report"],
        ["report_recommendations", "Taking everything into consideration,", "report"],
        ["conclusion", "These measures would, I believe, significantly...", "report"],
        ["report_findings", "According to a recent survey,", "report"],
        ["report_findings", "feedback suggests that...", "report"],
        ["cause_result", "This, in many cases, leads to...", "report"],
        ["cause_result", "which suggests a need for...", "report"],
        ["report_findings", "many students complained that...", "report"],
        ["report_findings", "were unaware that...", "report"],
        ["report_recommendations", "In light of these findings,", "report"],
        ["conclusion", "These steps would likely...", "report"],
        ["introduction", "The aim of this report is to compare...", "report"],
        ["report_findings", "on the one hand,", "report"],
        ["report_findings", "on the other hand,", "report"],
        ["report_findings", "by contrast,", "report"],
        ["addition", "as well as...", "report"],
        ["recommendation", "Having weighed up the options, I would recommend...", "report"],
        ["recommendation", "since...", "report"],
        ["conclusion", "With careful planning, this event could prove...", "report"],
    ];

    foreach ($expressions as $expr) {
        $stmt3->execute($expr);
    }
    
    echo "Database seeded successfully!\n";
} catch (PDOException $e) {
    die("Seeding failed: " . $e->getMessage());
}
